cloud:
  aws:
    credentials:
      access-key: AKIAXMCST5V3PWHLQILU
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: hometrainingbucket
    stack:
      auto: false

spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6739
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

